### ISSUE TITLE
[BUG] - submodule setup needs to be adjusted

### ISSUE THREAD

**Issue by mprather** [opencaesar/oml-luxor#12]
## Description
The submodule path is currently using an ssh address. The repo cannot be cloned as detailed in the readme. The clone command fails due to host key verification failure.  The current submodule enlistment basically forces SSH authentication. 

## Steps to Reproduce
- [ ] Follow the readme

Result:
Cloning into 'C:/src/oml-luxor/oml-sprotty'...
Host key verification failed.
fatal: Could not read from remote repository.

## Expected Behavior
The general recommendation for submodules is to use an https address for general use. Then only use ssh paths for developers. This makes cloning easier for non-contributors.

## Additional Context
Since the oml-sprotty repo uses the same parent as this repo, the path setting for submodule can be further improved by simply using a relative path.

> 	url = ../oml-sprotty.git

This would allow the submodule to be initialized to the same format as the parent clone (i.e. https or ssh).

**Comment by melaasar** [comment]
Goos suggestion. I implemented them. Thanks!
