### ISSUE TITLE
publish vscode extension to open vsx registry

### ISSUE THREAD

**Issue by akosyakov** [opencaesar/oml-luxor#4]
that it can be installed not only in VS Code

Registry: https://open-vsx.org/
Why: https://dev.to/svenefftinge/theia-1-0-finally-a-good-browser-ide-3ok0#open-vsx
How: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by CiaranMcAndrew** [comment]
Found here: https://open-vsx.org/extension/openCAESAR/oml-luxor

**Comment by melaasar** [comment]
As mentioned above, the OML Luxor extension is already published in the VSIX registry. It is also available for download from the Github releases (for installing in VS Code).
